### ISSUE TITLE
hi,i want to know how to use your example get the svg data which i draw on web?

### ISSUE THREAD

**Issue by nanmenxue** [tmerse/SVG_FONT#2]

**Comment by tmerse** [comment]
Hey there, thanks for your interest in my project. I am busy right now but will answer tomorrow.

**Comment by tmerse** [comment]
Once you hit the "export" button below the textbox inside the demo (http://tmerse.github.io/SVG_FONT/), the raw `svgData`-array will be displayed in the textbox.

The entries are mapped against the ascii table. So a svg-representation of your freshly drawn "a" will reside on the 97th index of the array. See

```
String.fromCharCode(97) // a
String.fromCharCode(98) // b
```

You may now use that svg-entry inside anything that can handle svg.
Did this answer your question?
